- hosts: localhost
  gather_facts: yes

  vars:
    var1: value1
    var2: value2

  tasks:
    - name: Do nothing
      ping:

    - name: Debug user_gecos
      debug:
        var: ansible_facts.user_gecos

    - name: Set some data to pass down to the 2nd AWS Job template
      set_stats:
        data:
          my_personal_variable: "{{ ansible_facts.user_gecos }}-papu"
